aa_platform:
    resource: "@AAPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

rest :
    type : rest 
    resource : "@AAPlatformBundle/Resources/config/routing_rest_v1.yml"
    prefix : /api/v1


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/doc


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"